[package]
name = "pelgaian"
version = "0.1.0"
edition = "2021"
description = "Pelgaian programming language interpreter"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "pelgaian"
path = "src/main.rs"